### ISSUE TITLE
Unable to complete the installation.

### ISSUE THREAD

**Issue by parvageshahariar** [LogiComposer/Try#3]
Hi,
I am trying to install in Ubuntu Bionic(18.04). I have installed docker and docker compose using the set up guide instruction. 
In the final step I got error and it stoped the installation. 

./try-logicomposer.sh: 20: [: up: unexpected operator

I have attached the screenshoot here too. Please check the below link

[https://paste.pics/FM11G](url)

**Comment by Niyakiy** [comment]
@parvageshahariar thanks for reporting the issue.
this repository was rebranded and is now available using 
https://github.com/LogiComposer/LogiComposerTrial
this link. The issue you've reported is already fixed there.
